# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-04 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cert',
            fields=[
                ('dgst', models.CharField(max_length=33, primary_key=True, serialize=False)),
                ('status', models.IntegerField()),
                ('sn', models.CharField(max_length=30)),
                ('sub', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=30)),
                ('cn', models.CharField(max_length=100)),
                ('notbefore', models.DateTimeField()),
                ('notafter', models.DateTimeField()),
                ('usage', models.CharField(max_length=30)),
                ('vtype', models.IntegerField()),
                ('ca', models.BooleanField()),
                ('alternative', models.TextField(null=True)),
                ('certfile', models.TextField()),
                ('issuer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ca.Cert')),
            ],
        ),
        migrations.CreateModel(
            name='PubKey',
            fields=[
                ('dgst', models.CharField(max_length=33, primary_key=True, serialize=False)),
                ('pub', models.TextField(null=True)),
                ('key', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='cert',
            name='key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ca.PubKey'),
        ),
    ]
