# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-05 08:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0002_auto_20180604_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cert',
            name='email',
        ),
    ]
