# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-05 08:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0003_remove_cert_email'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cert',
            unique_together=set([('issuer', 'sn')]),
        ),
    ]
