# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-07 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0004_auto_20180605_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cert',
            name='ca',
        ),
        migrations.RemoveField(
            model_name='cert',
            name='usage',
        ),
        migrations.RemoveField(
            model_name='cert',
            name='vtype',
        ),
        migrations.AlterField(
            model_name='cert',
            name='key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ca.PubKey'),
        ),
    ]
