# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-08 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0005_auto_20180607_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='pubkey',
            name='keytype',
            field=models.IntegerField(choices=[(1, 'RSAPrivateKey'), (2, 'RSAPublicKey'), (3, 'ECCPrivateKey'), (4, 'ECCPublicKey')], default=1),
            preserve_default=False,
        ),
    ]
