# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-08 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0006_pubkey_keytype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pubkey',
            name='pub',
        ),
    ]
