# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-08 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0007_remove_pubkey_pub'),
    ]

    operations = [
        migrations.AddField(
            model_name='pubkey',
            name='size',
            field=models.IntegerField(default=2048),
            preserve_default=False,
        ),
    ]
